# 项目配置
app:
  prefix: '/api'
  host: 'localhost'
  port: 3000
  # 数据库
db:
  mysql:
    type: mysql # 数据库链接类型
    host: localhost
    port: 3306
    username: 'root' # 数据库链接用户名
    password: 'root' # 数据库链接密码
    database: 'blog' # 数据库名
    entityPrefix: 'sys_' # 表名前缀
    logging: true # 数据库打印日志
    synchronize: true # 是否开启同步数据表功能
    autoLoadEntities: true # 是否自动加载实体
# 日志
log:
  level: 'info'
  on: true
  dir: 'logs'
  timestamp: true
#jwt 鉴权配置
jwt:
  secret: 'm5Hg7GuoJYO6uiXILqnXyqKQ1joRQ6YhoPBb6CUfV6p6qi1BBK2rt98RxRAs8Oi7i'
  expires: '1d'
  refresh: '7d'
# redis 配置
redis:
  host: 'localhost'
  port: 6379
  password: '123456'
  db: 0
  keyPrefix: 'nest:'

#  用户相关
# 初始密码， 重置密码
user:
  initialPassword: 'n123456'
